movie-knight/src/App.css, movie-knight/src/actions/index.js, movie-knight/src/components/Dashboard.js, movie-knight/src/components/Login.js, movie-knight/src/components/Signup.js, movie-knight/src/reducers/index.js, movie-knight/src/utils/axiosWithAuth.js
=> Authorization

movie-knight/package-lock.json, movie-knight/package.json, movie-knight/src/components/Login.js
=> started google login

movie-knight/src/App.css, movie-knight/src/actions/index.js, movie-knight/src/components/Nav.js, movie-knight/src/hooks/useDarkMode.js, movie-knight/src/hooks/useLocalStorage.js, movie-knight/src/reducers/index.js
=> spelling fix and dark mode

movie-knight/src/actions/index.js, movie-knight/src/components/Login.js
=> getting  google data

movie-knight/src/App.js, movie-knight/src/actions/index.js, movie-knight/src/components/Availability.js, movie-knight/src/components/Checkout.js, movie-knight/src/components/Event.js, movie-knight/src/components/Login.js, movie-knight/src/components/MakeSeatingChart.js, movie-knight/src/components/MovieDetails.js, movie-knight/src/components/Nav.js, movie-knight/src/components/OwnerDashboard.js, movie-knight/src/components/PrivateRoute.js, movie-knight/src/components/Signup.js, movie-knight/src/utils/axiosWithAuth.js
=> login + signup hooked with backend

movie-knight/package-lock.json, movie-knight/src/App.js, movie-knight/src/App.test.js, movie-knight/src/components/Login.js, movie-knight/src/components/Nav.js, movie-knight/src/components/OwnerLogin.js, movie-knight/src/components/OwnerSignup.js, movie-knight/src/index.js, movie-knight/src/reducers/index.js
=> all files is rending testing, and nav bug fixed

movie-knight/src/App.js, movie-knight/src/actions/index.js, movie-knight/src/components/movieDashboard/Dashboard.js, movie-knight/src/components/movieDashboard/MovieCard.js, movie-knight/src/components/movieDashboard/MovieList.js, movie-knight/src/components/movieDashboard/dashboard.css, movie-knight/yarn.lock
=> Movie dashboard

movie-knight/src/App.js, movie-knight/src/App.scss, movie-knight/src/components/DatePicker.js, movie-knight/src/components/Login.js, movie-knight/src/components/Signup.js, movie-knight/src/components/movieDashboard/Dashboard.js, movie-knight/src/components/movieDashboard/MovieList.js, movie-knight/src/components/movieDashboard/dashboard.scss
=> User next flow after picking movie to day pick page

movie-knight/public/index.html, movie-knight/src/App.scss
=> Fixed button size bug on iPhone

movie-knight/src/actions/index.js, movie-knight/src/components/movieDashboard/MovieCard.js, movie-knight/src/components/movieDashboard/MovieList.js
=> fixed merge error, combined hamburger menu and dynamic styling

movie-knight/src/components/movieDashboard/MovieList.js, movie-knight/src/components/movieDashboard/dashboard.scss
=> Changed movie card width to make two columns again

movie-knight/src/components/MovieDetails.js, movie-knight/src/components/movieDetails.scss
=> styling the movie Details Page

movie-knight/package-lock.json, movie-knight/package.json, movie-knight/src/App.scss, movie-knight/src/components/MovieDetails.js, movie-knight/src/components/Nav.js, movie-knight/src/components/movieDashboard/dashboard.scss, movie-knight/src/components/movieDetails.scss
=> loading in movie detail, movie poster fix in dashboard

movie-knight/src/components/Nav.js
=> fixed bug in hamburger menu, now will close when click on item

movie-knight/src/App.scss, movie-knight/src/components/Nav.js, movie-knight/src/components/movieDashboard/MovieList.js
=> Advanced filtering release date

movie-knight/src/App.scss, movie-knight/src/components/Signup.js, movie-knight/src/components/movieDashboard/dashboard.scss
=> added styling for signup and login

movie-knight/src/components/MovieDetails.js, movie-knight/src/components/movieDashboard/MovieCard.js, movie-knight/src/components/movieDashboard/dashboard.scss
=> adding movie rate to the movie details page

.github/workflow/ci.yml
=> moved .github folder up a level

movie-knight/src/actions/index.js, movie-knight/src/components/movieDashboard/Dashboard.js, movie-knight/src/components/movieDashboard/MovieCard.js, movie-knight/src/components/movieDashboard/MovieList.js, movie-knight/src/reducers/index.js
=> The Next button will only display after selecting a movie

movie-knight/src/components/movieDashboard/FilterMenu.js, movie-knight/src/components/movieDashboard/MovieList.js, movie-knight/src/components/movieDashboard/dashboard.scss
=> Advanced filtering

movie-knight/src/components/movieDashboard/dashboard.scss
=> fixing height of filtering menu

movie-knight/.github/workflows/ci.yml
=> if code climate want to work

movie-knight/src/App.js, movie-knight/src/actions/index.js, movie-knight/src/components/DatePicker.js, movie-knight/src/components/DayCard.js, movie-knight/src/components/TimeCard.js, movie-knight/src/components/TimePicker.js, movie-knight/src/components/movieDashboard/Dashboard.js, movie-knight/src/components/movieDashboard/MovieCard.js, movie-knight/src/components/movieDashboard/MovieList.js, movie-knight/src/reducers/index.js, movie-knight/yarn.lock
=> Date picker

movie-knight/src/components/movieDashboard/MovieCard.js, movie-knight/src/components/movieDashboard/MovieList.js, movie-knight/src/components/movieDashboard/dashboard.scss
=> can't select more than 3 movies!

.github/workflows/ci.yml
=> CodeClimate

movie-knight/src/App.scss, movie-knight/src/components/Nav.js, movie-knight/src/components/ProgressBar.scss, movie-knight/src/components/SeatChart.js, movie-knight/src/components/movieDashboard/MovieList.js, movie-knight/src/components/seatChart.scss
=> fixed build error

movie-knight/src/actions/index.js, movie-knight/src/components/SeatChart.js, movie-knight/src/components/SeatsCard.js, movie-knight/src/components/seatChart.scss, movie-knight/src/reducers/index.js
=> Seats Select

movie-knight/src/components/movieDashboard/FilterMenu.js, movie-knight/src/components/movieDashboard/dashboard.scss
=> possible fix to filter bug

movie-knight/src/components/Showtime.js, movie-knight/src/components/movieDashboard/MovieCard.js, movie-knight/src/components/showtime.scss
=> poster, name, runtime, rated is styled

movie-knight/src/App.scss, movie-knight/src/components/Showtime.js, movie-knight/src/components/Tickets.js, movie-knight/src/components/showtime.scss, movie-knight/src/components/tickets.scss
=> Showtime page

movie-knight/src/components/SeatChart.js, movie-knight/src/components/SeatsCard.js, movie-knight/src/components/seatChart.scss
=> fix seats bug

movie-knight/src/components/profile/Profile.js, movie-knight/src/components/profile/profileStyle.scss
=> Movies style

movie-knight/src/actions/index.js, movie-knight/src/components/DatePicker.js, movie-knight/src/components/DayCard.js, movie-knight/src/components/Showtime.js, movie-knight/src/components/TimeCard.js, movie-knight/src/components/TimePicker.js, movie-knight/src/components/movieDashboard/MovieCard.js, movie-knight/src/components/profile/profileStyle.scss, movie-knight/src/reducers/index.js
=> Movies ShowTime

movie-knight/src/App.scss, movie-knight/src/components/MovieDetails.js, movie-knight/src/components/ProgressBar.scss, movie-knight/src/components/movieDashboard/dashboard.scss, movie-knight/yarn.lock
=> minor styling

movie-knight/src/App.scss, movie-knight/src/components/DatePicker.js, movie-knight/src/components/ProgressBar.js, movie-knight/src/components/ProgressBar.scss, movie-knight/src/components/SeatChart.js, movie-knight/src/components/SeatsCard.js, movie-knight/src/components/Tickets.js, movie-knight/src/components/TimePicker.js, movie-knight/src/components/movieDashboard/Dashboard.js, movie-knight/src/components/movieDashboard/dashboard.scss, movie-knight/src/components/seatChart.scss, movie-knight/src/components/tickets.scss
=> user has to pick time, day and seat to proceed, and filter styling fix

movie-knight/src/components/MovieDetails.js, movie-knight/src/components/Tickets.js, movie-knight/src/components/movieDetails.scss, movie-knight/src/components/seatChart.scss, movie-knight/src/components/showTimes/Showtime.js, movie-knight/src/components/showTimes/showtime.scss, movie-knight/src/components/tickets.scss
=> progressbar center on all screen except

movie-knight/src/actions/index.js, movie-knight/src/components/profile/Profile.js, movie-knight/src/reducers/index.js
=> fixing profile bug

movie-knight/src/App.js, movie-knight/src/components/progress-nav-bars/Nav.js, movie-knight/src/index.js
=> Bug fix v2

movie-knight/public/index.html, movie-knight/src/App.scss, movie-knight/src/components/movieDashboard/FilterMenu.js, movie-knight/src/components/movieDashboard/dashboard.scss, movie-knight/src/components/progress-nav-bars/Nav.js, movie-knight/src/components/seats/seatChart.scss, movie-knight/src/components/showTimes/showtime.scss, movie-knight/src/components/tickets/tickets.scss
=> Navbar with background and filter see results close filter after clicked

movie-knight/src/actions/index.js
=> fix bug in theatre component

movie-knight/src/App.scss, movie-knight/src/components/movieDashboard/dashboard.scss, movie-knight/src/components/progress-nav-bars/Nav.js, movie-knight/src/components/seats/seatChart.scss, movie-knight/src/components/showTimes/TimesCard.js
=> navbar fix if user is log in, some stling, and 24 hours to 12

movie-knight/src/actions/index.js, movie-knight/src/components/movieDashboard/ZipSearch.js, movie-knight/src/components/showTimes/Showtime.js, movie-knight/src/reducers/index.js
=> fixing bugs
